name: tuneup
description: A command-line tool to manipulate and inspect your Dart projects.

# This version must be updated in tandem with the lib/tuneup.dart version.
version: 0.3.7
homepage: https://github.com/google/tuneup.dart

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  analysis_server_lib: ^0.1.4
  args: ^1.0.0
  cli_util: ^0.2.0
  intl: '>=0.15.0 <0.17.0'
  logging: ^0.11.0
  path: '>=1.4.0 <2.0.0'
  yaml: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0

# Add the bin/tuneup.dart script to the scripts pub installs.
executables:
  tuneup:
